### ISSUE TITLE
Switch datasets -> "show dataset" in new window

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#103]
Hi,

I suggest to open a datset automatically in a new window (that should then be called accordingly) when clicking "switch" dataset (-> rename that button). Or making this optional

This would:
- enable to browse several datasets in parallel to compare morphologies
- make it more consistent with BDV-playground behaviour.

When a switch from one to the other dataset is wanted, the user can just close that BDV window.

**Comment by constantinpape** [comment]
@tischi and me also discussed this, but decided not to do this for now, because it would be confusing:
for every new dataset a lot of different windows would be opened:
- the main viewer
- the gui to select which layers to open
- separate tables for each segmentation
- the 3d object viewers
- ...

So before doing this, we would like to integrate more of the functionality into a single window, which should be possible with the new bdv core.

**Comment by martinschorb** [comment]
solved with exclusive views.
