### ISSUE TITLE
Manual registration, close original sources

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#1169]
Hi,
 could the original moving source be removed when the transformation is accepted? Then the active viewer would immediately show the result and not a duplicated source (original + transformed).

**Comment by tischi** [comment]
I can easily make the original source invisible. What is a bit more tricky is to fully remove it, because one display settings UI element can correspond to multiple sources (e.g. in a grid view), and then maybe one does not want to remove all of them. But I could check that there in fact is a one-to-one mapping and only then remove it.

**Comment by martinschorb** [comment]
I guess making it invisible should be sufficient.

**Comment by tischi** [comment]
Hi @martinschorb, 

I uploaded a new version where the non-transformed input sources and their corresponding display UI items should be removed once the transformations are accepted.

Please test it.

**Comment by martinschorb** [comment]
tested, works!

**Comment by martinschorb** [comment]
When doing this for BigWarp and choosing multiple moving sources, it closes all but the last saved transformed source. I would expect to keep all transformed moving sources.

**Comment by martinschorb** [comment]
plus, it also closes the sources when not saving them and clicking `Cancel`

**Comment by martinschorb** [comment]
I think it even saves the transformed source view when clicking `Cancel` in the save view dialog
