### ISSUE TITLE
Fetch persisted SciJava Command parameters programmatically

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1197]
Hi @ctrueden,

@ekatrukha and I need to fetch the persisted parameters value of a SciJava Command, in our case  it is called`ConfigureBVVSettingsCommand` programmatically. Is that possible? 

The use-case is that we want to apply the settings from the last session to our BigVolumeViewer instance upon startup of new MoBIE instance, even if a user did not yet launch the `ConfigureBVVSettingsCommand` in that session.

**Comment by ctrueden** [comment]
@tischi Maybe this Groovy script helps you?

```groovy
#@ CommandService cs
#@ ModuleService ms

// Get persisted value of a command parameter.
import org.scijava.plugins.commands.debug.ParamAssignOrder
info = cs.getCommand(ParamAssignOrder.class)
item = info.getInput("input1")
value = ms.load(item)
println("--> $value <--")

def menuLabel(info) {
	path = info.getMenuPath()
	if (path == null) return null
	leaf = path.getLeaf()
	return leaf == null ? null : leaf.getName()
}

// Look up a non-command module (e.g. a script) by menu path.
modules = ms.getModules()
correctDrift = modules.stream().filter { "Correct 3D drift".equals(menuLabel(it)) }.findFirst().get()
println(correctDrift)
correctDrift.getInput("Oh no this uses GenericDialog we're hosed")
```

**Comment by ekatrukha** [comment]
Hello @ctrueden,

thank you for your help!
So we want to get these values not in another command, 
but in a method of a class or while constructing a new object.

I tried something like this
```
Context ctx = new Context();

CommandService cs = ctx.getService( CommandService.class );
ModuleService ms = ctx.getService( ModuleService.class );

CommandInfo info = cs.getCommand( ConfigureBVVRenderingCommand.class );
CommandModuleItem< ? > item = info.getInput( "InputValue1" );
```

But it seems that the `Context` is not the same, the value of `item` is `null`.
What is the next way to get it at the runtime?

**Comment by tischi** [comment]
@ekatrukha 
For the command service,  could you please try:
`org.embl.mobie.lib.Services.CommandService`
If that works better we can probably also add the `ModuleService` there.

**Comment by ekatrukha** [comment]
Hello @tischi 

Thank you, that works!
For the `ModuleService`, I can obtain it via
```
CommandService cs = Services.commandService;
ModuleService ms = Services.commandService.moduleService();
```

@ctrueden I don't know if this correct, but in my hands
if the `Command` has never been executed by user (or me  :) before, 
I have to do
```
item = info.getInput( "InputName" );
if(ms.load( item ) == null)
{
	InputNameVar = ( double ) ms.getDefaultValue( item );				
}
else
{
	InputNameVar = ( double ) ms.load( item );
}
```

Please, let me know if you have more elegant solution for this that I overlooked.

**Comment by ctrueden** [comment]
@ekatrukha Your code looks fine to me: first try loading the persisted value, but if there isn't one, fall back to the default value.

But there will still be edge cases where the value that *would have been shown* in an input harvester dialog does not match what you compute using this logic. The reason is that module execution has a *preprocessing chain* that is also plugin-based, so anyone could write plugins to populate and/or modify the input values of a to-be-executed module however they like. A common example is the suite of "single input" preprocessor plugins, which autofill parameters like `Dataset` with the active image when there is only one such parameter in the module.

If you need to calculate the exact same thing that would have been shown in the input harvester, what you can do is something like:

```java
List<? extends PreprocessorPlugin> pre = pluginService.createInstancesOfType(PreprocessorPlugin.class);
List<PreprocessorPlugin> preGood = new ArrayList<>();
for (PreprocessorPlugin pp : pre) {
  if (pp instanceof InputHarvester) break;
  preGood.add(pp);
}
```
and then you have a list of preprocessor plugin instance that operate on modules before execution.

And then you can just run the preprocessing chain:
```java
ModuleInfo info = ...; // as above
Module m = moduleService.createModule(info);
ModuleRunner runner = new ModuleRunner(ctx, m, pre, null);
runner.preProcess();
```

And then you can pull the values out of the module:
```java
Map<String, Object> inputs = m.getInputs();
```

Doing it this way will encompass restoration of previously persisted values, other autofill mechanisms such as the single-input preprocessors, and falling back to default values as appropriate.

But we have now drifted quite some ways away from the stated issue here of simply fetching persisted values from the disk storage. :wink:

**Comment by ekatrukha** [comment]
I think we can close it now.
