### ISSUE TITLE
update parent-pom to ??

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#1206]
Hi @ekatrukha,

I see that Fiji now ships with [scijava 39.0.0](https://github.com/fiji/fiji/blob/master/pom.xml#L8).

However, MoBIE still is on [scijava 37.0.0](https://github.com/mobie/mobie-viewer-fiji/blob/main/pom.xml#L7).

Do you think that could be an issue? I think there have been some breaking changes in ImgLib2.

I found that we have a MoBIE branch `scijava-39.0.0`, so I probably have started to work on migrating...to finish this I think I want need to remove the [imagej-utils dependency](https://github.com/mobie/mobie-viewer-fiji/blob/main/pom.xml#L87), which also still relies on scijava 37.0.0. **imagej-utils** is one of my own repos but it becomes too annoying to maintain, so I want to copy everything into MoBIE that is needed and then discontinue that repo.

I also found that there is a `scijava39` branch of mobie-io; so would need to use that.

@ekatrukha do you have any thoughts about migrating to scijava 39.0.0? To be honest, I am surprised that MoBIE still seems to work with a fresh Fiji install...

I see that @nicokiaru [posted that he reverted to scijava 38.0.1](https://forum.image.sc/t/fiji-friends-weekly-dev-update-thread/103718/34)...I wonder what is that about?

...actually I am very confused now, because scijava-39.0.0 should be that one that is used for "Fiji future"...so it should not be that basis of the current Fiji...

[I am asking on Zulip...](https://imagesc.zulipchat.com/#narrow/channel/327238-Fiji/topic/Which.20parent.20pom.20is.20currently.20used.20to.20deploy.20Fiji.3F)

**Comment by ekatrukha** [comment]
Hello @tischi,

as I explained on zulip, pom 39 is not included in current Fiji. 
What is on github does not mean it is in the distribution, you need to download Fiji and check its version, find back on github its pom.

In my opinion, for the user's convenience, it is a good practice to use current (downloadable distribution) Fiji (2.14) pom (36.0.0).
You can also use 37 or 38, it seems that they are mostly compatible with it.

The recent problem happened because BigStitcher update site (used by many people) started to "shadow" (re-write) imglib2 library to version 7, while the one shipped with the current downloadable Fiji is v6.
This causes other plugins to fail, since v6 to v7 has some breaking changes.
v7 will become (or already is) a part of pom 39, but it is not in the distribution yet.
But one can start to prepare since it is going to be the base of Fiji Future (or at least its first version).

I think this is why @NicoKiaru reverted back to pom 38 (compatible with 36), otherwise he had to upload (shadow) imglib7.

Cheers,
Eugene

**Comment by tischi** [comment]
Thanks for the insights @ekatrukha ! 

Let's maybe continue the discussion on Zulip, OK?

**Comment by ekatrukha** [comment]
Yep, I agree.
