### ISSUE TITLE
Bookmark settings persist in source metadata

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#133]
Viewing a bookmark currently modifies the sources' metadata - this means that these settings persist in the current session. e.g. If you open the platybrowser, view the bookmark for figure 5C, then remove the cell segmentation from the viewer. Every time you add the cell segmentation after that it will add the additional tables from the bookmark /  colour by column etc..

@tischi - could we possibly separate the default metadata for a source (i.e. from images.json), from the current metadata? This would stop the bookmark settings from persisting, and make it easier to save the current settings to bookmarks. e.g. we could add another Metadata entry into the SourceAndMetadata class?

**Comment by tischi** [comment]
Thank for spotting this! I would almost call it a bug.

It is a bit tricky though, because maybe some modified metadata we want to persist, e.g. if a user change the brightness and contrast display settings.

But for sure I would agree that the metadata changes from a bookmark should not persist.

In fact, the whole `Metadata` class is a bit of a mess, grown historically.

Within MoBIE I tried to improve the situation a bit with those classes: `ImageProperties` and `MutableImageProperties`. But since the imagej-utils code has legacy issues (I also use it in other projects) I had to still use the `Metadata` class in the end and I think for now we have to live with it.

Would the following work?

In `Bookmarksmanager` there is this function, where I am proposing some changes

```
	public void addSourcesToPanelAndViewer( Bookmark bookmark )
	{
		for ( Map.Entry< String, MutableImageProperties> newSettings : bookmark.layers.entrySet() )
		{
			final String sourceName = entry.getKey();
			if ( ! sourcesPanel.getVisibleSourceNames().contains( sourceName ) )
			{
                                // change metdata to reflect what is demanded by the boomark and remember the old settings
				MutableImageProperties oldSettings =  updateSourceMetadataAndFetchPerviousSettings( newSettings, sourceName );
                                // show the source
				sourcesPanel.addSourceToPanelAndViewer( metadata.displayName );
                                /// ??? reset the metadata to what was before
                                updateSourceMetadataAndFetchPerviousSettings( oldSettings, sourceName );
			}
		}
	}
```

Something like this? Do you think that could work?

**Comment by K-Meech** [comment]
Ok - makes sense! This would work.
I see though that, at the moment, some of the changes you make in the viewer persist and some don't. e.g. changing the colour of a source modifies the metadata, but modifying the brightness does not. If you remove sources and add them again, it's pretty much just loading the default metadata (as none of the changes like brightness, adding tables, colouring by columns etc are recorded in the metadata).

I just wonder if we could keep the metadata class exactly as it is currently, but instead have two instances for each source. One for default (what to load when you add a source) and one tracking the current state e.g. all the colouring by columns, tables etc etc Then, for changes you want to persist, you can modify the default, but for the rest only modify the current metadata? I get if we can't do this for legacy reasons / breaking other code!

It would make it a lot easier to save the current state to bookmarks though. Currently, you have to dig through all the different objects to find that info, as none of it ends up in the metadata.

**Comment by tischi** [comment]
> I just wonder if we could keep the metadata class exactly as it is currently, but instead have two instances for each source. One for default (what to load when you add a source) and one tracking the current state e.g. all the colouring by columns, tables etc etc

Maybe that is easier indeed. 

You could then just somewhere have two global maps 
`Map< Source, Metadata > sourceToDefaultMetadata`
`Map< Source, Metadata > sourceToCurrentMetadata`
and then work like this?

If you don't want to change the current code too much you could then just instantiate new `SourceAndMetadata` objects for the appropriate current use cases, for example

```
addSourceToPanelAndViewer( new SourceAndMetadata( source, defaultMetadata ) );
```
or
```
addSourceToPanelAndViewer( new SourceAndMetadata( source, bookmarkMetadata ) );
```

For this, you would need to write a few classes that generate _new_ `Metadata` objects (rather than modifying).

Not sure if that's what you had in mind?

**Comment by K-Meech** [comment]
Sounds good to me! I'll give this a go. 
I'm modifying this as part of changes for the bookmark UI, so it'll go in a pull request with all of those changes.

**Comment by tischi** [comment]
In principle it would be cool to only have the `MutableImageProperties` changing are the other ones should not change.
Maybe thus the global maps could work with the `MutableImageProperties` class and you on-the-fly convert to `Metadata` when you need it? Just an idea. A bit more work but long term maybe cleaner.

Also: The bookmarks use the `MutableImageProperties` class in terms of from and to Json so I think you would need this anyway.

**Comment by K-Meech** [comment]
Good point - makes sense to use MutableImageProperties where possible. 
The issue I'm having now, is that keeping the currentMetadata up to date is quite difficult. e.g. some calls like colorByColumn / adjusting the valueLimits from the table menu happen entirely in the imagej-utils table code. So triggering updates to metadata within mobie's sourcesPanel is difficult. Any ideas?

Might have to leave this for now, and just directly read that information when you want to save bookmarks.

**Comment by tischi** [comment]
> So triggering updates to metadata within mobie's sourcesPanel is difficult. Any ideas?

We can fix this later....I hope.

Maybe just pretend for now that the `MutableImageProperties` (or `MetaData`) are always up to date and get the rest of the code working?

Maybe let's make a list:

- [X] `setSourceColor` this seems to be updated properly already, right?
- [X] `createBrightnessButton` this should also work, because the current settings are accessible via `sam.metadata().bdvStackSource` (`getConverterSetups( sam.metadata().bdvStackSource )`)

#### Table stuff

There is already:

`sam.metadata().views.getTableRowsTableView()` 

You would just have to add `getter` methods to the `TableRowsTableView` in `imagej-utils` to be able to fetch all the current settings that you want to store in the bookmark. Makes sense?

**Comment by K-Meech** [comment]
Thanks for the pointers - I had a look yesterday, and I think I can update most of the settings now. I'll get the rest of the code working, and then we can fix the last few.

**Comment by tischi** [comment]
>  I think I can update most of the settings now

In principle you only have to do this, when a user wants to create a bookmark, right?

I would imagine code like this:

1. Create bookmark
2. Loop through all currently visible sources and create `MutableImageProperties` for them
3. Save a json file

Is that correct or am I missing something?

**Comment by K-Meech** [comment]
Yes - we only need to do this when a user wants to make a bookmark. It's only complicated if there are properties we can't read directly at that moment e.g. I don't think there's an easy way to access which extra tables are currently loaded

**Comment by tischi** [comment]
> I don't think there's an easy way to access which extra tables are currently loaded

The `TableView` class could keep track of this and then provide a `get` method for this information. 
Would that work? Could you add it?

**Comment by K-Meech** [comment]
Sure - that would work! I'll add it
