### ISSUE TITLE
Movies demonstrating the functionality

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#165]
@vzinche @K-Meech @yanschwab

I have to give a short talk about MoBIE early next year.

My plan is to essentially show the audience a couple of YouTube videos demonstrating the functionalities.

This is what I have already:
- https://www.youtube.com/watch?v=tdOLelm6Vlw
- https://www.youtube.com/watch?v=4SR5GoSiCVE
- https://www.youtube.com/watch?v=HENo-vq-6to

I would like to add
- [ ] Loading a cool bookmark (with 3D objects)
- [ ] Doing something nice with the interactive scatterplot

1. Regarding the bookmark and the scatterplot, do you have ideas for concrete storyboards?
2. Do you have other suggestions for what to show?

**Comment by vzinche** [comment]
For the interactive scatterplot I can suggest what I've shown during the unit seminar:
- We have some morphological features we want to explore
- We make a UMAP and visualize it in the platy browser
-  We color it by gene expression
- We find some interesting subgroup of cells
- We use the interactivity to find them in the BDV
- Pampam! It's photoreceptors

Slides:
[photoreceptors.pdf](https://github.com/mobie/mobie-viewer-fiji/files/5723125/photoreceptors.pdf)
!

**Comment by K-Meech** [comment]
Sounds great!
For cool bookmarks with 3D objects: maybe the nephridia segmentation? Bookmark "Figure 2D: Nephridia segmentation" in the platybrowser has some nice 3D.
Otherwise, perhaps the covid paper guys have some nice 3D examples? 

If you need more UMAP examples, there's also the gene expression & morphology UMAPs I did for the platy paper. So could e.g. show UMAP of calculated morphology features / colour by our labelled cell types / interactively show where they are in the platy
