### ISSUE TITLE
G-zip corrupt error

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#174]
@constantinpape 

Have you ever seen this?

```
Caused by: java.io.IOException: Gzip-compressed data is corrupt
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.read(GzipCompressorInputStream.java:316)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at org.janelia.saalfeldlab.n5.DefaultBlockReader.read(DefaultBlockReader.java:51)
	at org.janelia.saalfeldlab.n5.DefaultBlockReader.readBlock(DefaultBlockReader.java:91)
	at org.janelia.saalfeldlab.n5.s3.N5AmazonS3Reader.readBlock(N5AmazonS3Reader.java:252)
	at de.embl.cba.mobie.n5.N5ImageLoader$N5CacheArrayLoader.loadArray(N5ImageLoader.java:321)
	at bdv.img.cache.VolatileGlobalCellCache.lambda$createImg$1(VolatileGlobalCellCache.java:246)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.lambda$get$0(LoaderCacheKeyAdapter.java:22)
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:102)
	... 24 more
```

**Comment by constantinpape** [comment]
Yes, this can happen with corrupted chunks.
Which data are you trying to open?

**Comment by tischi** [comment]
EM-Raw Platy.

Roughly this view at resolution 100 nm:
![image](https://user-images.githubusercontent.com/2157566/105976540-949ff480-6090-11eb-99f5-111cf9648b32.png)

**Comment by tischi** [comment]
I think it only happens when trying to access the highest resolution.

**Comment by constantinpape** [comment]
Ok, I will implement something to verify chunks.

**Comment by constantinpape** [comment]
Ok, I implemented some code to check for corrupted chunks and ran it in the first few scales, but couldn't find anything wrong.
Can you reliably reproduce this?

**Comment by tischi** [comment]
> Can you reliably reproduce this?

It happened twice today, both times when I tried making a screenshot from the platy with a pixel size of 10 nm (0.01 um).

**Comment by constantinpape** [comment]
Ah, makes sense; I confused highest scale and highest resolution.
I will run it for the highest resolution then, but it might take some time...

**Comment by constantinpape** [comment]
I have implemented a script now that goes through all the chunks on s3 and then replaces the corrupted ones with the local version.
For the platybrowser data I ran this for everything but the raw data now (currently under way, but will take a few days).
Btw, I think the data corruption happened when we had the similar issues with the covid data, but we just haven't noticed yet for the platy data, because it did not affect it as much.

Unfortunately data corruption is a more general issue and it would be good if the mobie-viewer could handle it more gracefully.
@tischi would it be possible to catch the `java.io.IOException: Gzip-compressed data is corrupt` exception somehow, treat the chunk as empty and then just log a warning, indicating which chunnks are corrupted? Then the viewer would still be usable when the data has some corrupted chunks.

**Comment by tischi** [comment]
Good idea, I can have a look.
Any chance you can create a test data set where that happens a a defined location?

**Comment by constantinpape** [comment]
> Any chance you can create a test data set where that happens a a defined location?

Yes, no problem. I will do that later and let you know once it's there.

**Comment by tischi** [comment]
@constantinpape 

I am catching now the error, returning a block of zeros and printing to the log window:
```
Error loading setup0/timepoint0/s2, [0, 1, 0]: java.io.IOException: Input is not in the .gz format
Error loading setup0/timepoint0/s2, [1, 1, 1]: java.io.IOException: Input is not in the .gz format
Error loading setup0/timepoint0/s1, [1, 0, 2]: java.io.IOException: Input is not in the .gz format
Error loading setup0/timepoint0/s0, [4, 2, 4]: java.io.IOException: Input is not in the .gz format
```
I already pushed the change to the main update site.

**Comment by constantinpape** [comment]
Great! Also most of the platy data is fixed now; raw data should be done in a couple of days.
