### ISSUE TITLE
set default image 

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#253]
Hi,

in `datasets.json` the default dataset is specified.

Could the same happen in `images.json` as well?  Right now the image that is shown on startup is the first one alphabetically. It would be nice to have some way of specifying it other than renaming.

**Comment by constantinpape** [comment]
> Could the same happen in `images.json` as well? Right now the image that is shown on startup is the first one alphabetically. It would be nice to have some way of specifying it other than renaming.

No, it's not alphabetic right now, but there is a default bookmark that is used. This is created automatically in mobie-utils-python, and probably is alphabetic for you because you add images in an alphabetic order.
`images.json` is deprecated, in the new spec the corresponding thing is `dataset.json`, which is in the top-level directory of a dataset. It contans `views`:`default`, which specifies the default view.

**Comment by constantinpape** [comment]
We already have an issue about enabling to change the default bookmark #193, so I am closing this one.
