### ISSUE TITLE
Dealing with additional tables for segmentation displays with multiple sources

### ISSUE THREAD

**Issue by K-Meech** [mobie/mobie-viewer-fiji#291]
Segmentation displays can potentially have many sources e.g. 
```
"segmentationDisplay": {            
      "lut": "glasbey",           
       "name": "segmentations",           
       "opacity": 0.5,            
       "sources": [  "segmentation1", "segmentation2", "segmentation3"  ],
       "tables": [ "table1", "table2" ]   
}

```

This creates issues with loading additional tables.

e.g. we currently specify tables as a list of names in the display. This means we don't know which folder to load these tables from, as there are multiple sources with different table locations. Could we change it so each added table is associated with a source name?

Also, when we 'load columns...' from a project, there are potentially many table folders to choose from (one for each source). So we'll probably need to add an extra step where you specify which source you want to add a table for.

@tischi @constantinpape  thoughts?

**Comment by constantinpape** [comment]
> This creates issues with loading additional tables.
> 
> e.g. we currently specify tables as a list of names in the display. This means we don't know which folder to load these tables from, as there are multiple sources with different table locations. Could we change it so each added table is associated with a source name?

When writing the spec, I thought that specifying additional tables for multiple segmentation sources means that all of them will load additional tables of the given names. For example, the display you have specified would only be valid if all 3 segmentations have a "table1" and a "table2" in their table folder.
For segmentations that load different tables, the idea was to provide different displays, e.g.
```yaml
[
{"segmentationDisplay": {"name": "segs-table1", "sources": ["seg1", "seg2"], ["table1", "table2"]},  # both segmentations will load the table "table1" and "table2" from their respective table folder
{"segmentationDisplay": {"name": "segs-table2", "sources": ["seg3"], ["table1"]}  # segmentation3 only loads "table1"
]
```

Would that work?

> Also, when we 'load columns...' from a project, there are potentially many table folders to choose from (one for each source). So we'll probably need to add an extra step where you specify which source you want to add a table for.

I am not quite sure if I understand this problem correctly, but the "load columns ..." should be w.r.t. a source and not w.r.t. a display, so the table folder should be uniquely identified.

**Comment by K-Meech** [comment]
Ah ok - makes sense! Yes that should work; I'll check it's enforced in the code that way.
The second point is then not an issue, as the tables are uniquely identified.

**Comment by K-Meech** [comment]
Actually, this would need a bit of adaptation.
When we 'load columns...' from the table menu, it currently just lists all the tables available in one table directory. 
To be consistent (and so we can save it as a bookmark later), when there are multiple sources in a segmentation display this should list only the tables that are common to all table directories.

**Comment by constantinpape** [comment]
> Actually, this would need a bit of adaptation.
> When we 'load columns...' from the table menu, it currently just lists all the tables available in one table directory.
> To be consistent (and so we can save it as a bookmark later), when there are multiple sources in a segmentation display this should list only the tables that are common to all table directories.

I think I still don't quite understand this. Maybe it would be good to discuss this via zoom. I would have time tomorrow any time after 10.

**Comment by K-Meech** [comment]
Sure - 11 works for me. I'll send you a zoom link

**Comment by constantinpape** [comment]
@tischi do you have time at 11 as well? If not Kimberly and me can also discuss this first and then summarize our results in this issue.

**Comment by constantinpape** [comment]
Ok, we resolved this:
the issue is that when having multiple segmentations as sources in a single view and then loading different columns for the tables of these segmentations, we obtain a view that cannot be expressed in the current spec (as a single view).
Note that it's possible to express this situation in the spec, but for this more than one view are necessary.
There are 3 potential solutions:
1. Change the spec, so that the tables are listed per source instead of for all sources.
2. Separate the view into multiple views in Fiji when a user tries to save a view with inconsistent tables.
3. Don't serialize views with inconsistent tables and warn the user (+ inform him which tables need to be removed to save the view).

We decided to go with option 3, because this case will only come up if a user interacts with some complex view loaded from a bookmark, loads additional tables and tries to save the view again. Hopefully this should happen rather infrequently. (Also, there are other cases when we can't serialize the view with tables, e.g. when the user has loaded a custom table from the file system).

**Comment by K-Meech** [comment]
I just realised there is still one issue for this. 
When you choose to load columns from a multi-segmentation table, I have to know which table folder to let the user choose tables from. So I can either:
- add an extra step where you choose the source you want to add tables for
- list tables in all the table directories (for all segmentations) - but then I would still need to indicate the name of the source somehow, otherwise this will be confusing for tables that are named the same in multiple folders

Either way we still don't allow the resulting view to be serialised + warn the user as to why.

**Comment by constantinpape** [comment]
> When you choose to load columns from a multi-segmentation table, I have to know which table folder to let the user choose tables from.

Ok, I still don't quite understand this part. I thought that also when having multiple segmentations in one view, with added "tables from project", we will still have separate tables for these segmentations in the UI. They will just load tables of the same name.

I tried to draw this situation:
![20210608_121248](https://user-images.githubusercontent.com/4263537/121168711-8e4a3200-c853-11eb-894f-8f846ab1d0c6.jpg)

I.e. we should have two separate tables in the UI, and it should be clear which source they are associated with (and this source is then used for loading additional tables from project).
Or am I missing something here?

**Comment by constantinpape** [comment]
Ok, I see. Grid views complicate everything a bit more... I think we have never really defined so precisely what should happen here and before we think about the concrete "load from project" functionality, we should discuss this.
I will do this in a separate issues because laying out the different options will be quite long...

**Comment by K-Meech** [comment]
This is resolved in the current master. Only tables that are present in all table folders (for a multi-source table) can be added.
