### ISSUE TITLE
View saving

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#371]
@K-Meech 

The GUI asks at the very end for the "view name". I think it would be easier to use if that was in the same UI where one chooses the "exclusive" and the "include viewer transform".

**Comment by constantinpape** [comment]
There are also some more issues with the generated views (copied from https://github.com/mobie/open-organelle-test/issues/1):
- sources in `"imageDisplays"` are saved as `"sources": ["image 0"]` instead of `"sources": ["<SOURCE NAME>"]` 
- `color` is saved as "(r\u003d0,g\u003d255,b\u003d0,a\u003d255)" but should be of the form "r=1,g=1,b=1,a=1"
- also, the file is saved with tabs; it would be nicer to use 2 spaces as indentation instead (which is what I do in python)

Note that you can use [mobie.validation.validate_view_metadata](https://github.com/mobie/mobie-utils-python/blob/spec-v-02/mobie/validation/metadata.py#L104) from the python tools to check if views are correct.

**Comment by K-Meech** [comment]
Ok - I'll look into these issues! I should have some time tomorrow ( linking this issue for other bookmark issues: https://github.com/mobie/mobie-viewer-fiji/issues/358)

**Comment by K-Meech** [comment]
> * sources in `"imageDisplays"` are saved as `"sources": ["image 0"]` instead of `"sources": ["<SOURCE NAME>"]`

This seems to be an issue with how a ```spimSource``` is assembled when reading this openOrganelle data. I grab the source names by doing: 

```
for ( SourceAndConverter< ? > sourceAndConverter : imageDisplay.sourceAndConverters )
		{
			sources.add( sourceAndConverter.getSpimSource().getName() );
		}
````

Usually, the spimSource has the same name as the source. But here, for the openorganelle data, the name is 'image 0' - hence the mismatch in the bookmark.

@tischi - would it be possible to match the source name in the spimSource when reading this data?

**Comment by tischi** [comment]
> would it be possible to match the source name in the spimSource when reading this data?

I pass the ball to @KateMoreva who wrote the loader for this data: could we set the source name during loading?

**Comment by KateMoreva** [comment]
> @KateMoreva I just tried it with the latest mobie master, and the name of the source is still 'Image 0'
> ![Screenshot (333)](https://user-images.githubusercontent.com/24316371/126983802-3ba22397-92d4-483e-b38c-a1dd22353852.png)

@K-Meech, ok, thank you, I'll try to solve the problem.

**Comment by KateMoreva** [comment]
> @KateMoreva I just tried it with the latest mobie master, and the name of the source is still 'Image 0'
> ![Screenshot (333)](https://user-images.githubusercontent.com/24316371/126983802-3ba22397-92d4-483e-b38c-a1dd22353852.png)

Should be solved in https://github.com/mobie/mobie-viewer-fiji/pull/386

**Comment by K-Meech** [comment]
Great - thanks @KateMoreva!
