### ISSUE TITLE
beta: Save current Settings as view - cannot load such a view properly

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#454]
When loading back a view saved through the right click functionality, I have the following issues (all using the filesystem to store the JSONs):

- 'Load additional view' does not do anything.
- Pasting the view into `dataset.json` leads to the entry showing up in the MoBIE GUI, but when loading it from there, I get:

```
Exception in thread "Thread-18" java.lang.NullPointerException
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.adaptConverter(ImageSliceView.java:89)
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.show(ImageSliceView.java:59)
	at org.embl.mobie.viewer.bdv.view.ImageSliceView.<init>(ImageSliceView.java:48)
	at org.embl.mobie.viewer.view.ViewManager.showImageDisplay(ViewManager.java:305)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:272)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:227)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$1(UserInterfaceHelper.java:454)
	at java.lang.Thread.run(Thread.java:748)

```

To recreate:
https://github.com/mobie/clem-example-project/tree/spec-v2

the view:
https://github.com/mobie/clem-example-project/blob/a3fccf72e3cee9df4e493bb7c997ebd6e15295f8/data/hela/dataset.json#L884

the exported view:
https://github.com/mobie/clem-example-project/blob/spec-v2/data/hela/clem53.json

**Comment by tischi** [comment]
@K-Meech Is it ok, if you have a look at this first?

**Comment by K-Meech** [comment]
I'll take a look @tischi. Thanks for reporting @martinschorb!

**Comment by K-Meech** [comment]
Ok - I found the issue. This happens because there are sources where the source name isn't the same as the xml file name e.g. here https://github.com/mobie/clem-example-project/blob/a3fccf72e3cee9df4e493bb7c997ebd6e15295f8/data/hela/dataset.json#L56. At the moment, I grab source names here: https://github.com/mobie/mobie-viewer-fiji/blob/master/src/main/java/org/embl/mobie/viewer/display/ImageSourceDisplay.java#L72 by getting the name directly from the spimSource. This will be == the xml filename, and not the mobie source name. Hence the errors.

So @tischi - we either need to find a way for the spimSource name to be equal to the mobie source name. OR there needs to be some way to fetch the mobie source name from an imageSourceDisplay. e.g maybe this (https://github.com/mobie/mobie-viewer-fiji/blob/70a4aa94fd955336f53254558562ae7f502c95fd/src/main/java/org/embl/mobie/viewer/display/AbstractSourceDisplay.java#L30) could become a map of source name to SourceAndConverter??

**Comment by K-Meech** [comment]
@tischi - are you fine if I change the 'sourceAndConverters' field in the AbstractSourceDisplay to be a map of mobie source name to SourceAndConverter?

**Comment by tischi** [comment]
Yes, totally, this matches much better how I refactored the rest of the code.

**Comment by K-Meech** [comment]
@martinschorb - this should be fixed on our current develop branch now (which will be on mobie-beta soon). You'll need to save the view again, and delete the one you made before. Then you should be able to 'Load additional view...'. This will load the views in the chosen file into the relevant ui selection groups - you'll then need to select them as usual to display them.

Feel free to re-open if there are more issues with this.
