### ISSUE TITLE
Move tests to src/test

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#523]
@K-Meech 
We should move your test classes to `src/test`.
You could do this in the `tests` branch that I am currently working on.
I will then pull your changes.

**Comment by K-Meech** [comment]
Which tests do you mean? The only tests I added were for the project creator, and they are all under src/test already here: https://github.com/mobie/mobie-viewer-fiji/tree/tests/src/test/java/org/embl/mobie/viewer/projectcreator. By default, in intellij when you do alt+enter on a class name, and create a test it puts it in src/test with the folder structure matching where the class is (so that's why it's under org/embl/mobie/viewer etc... inside src/test).

Would you prefer them in some different sub-folder of src/test?

**Comment by tischi** [comment]
I see! My bad!
