### ISSUE TITLE
Screenshot : add scale bar

### ISSUE THREAD

**Issue by vzinche** [mobie/mobie-viewer-fiji#562]
It is really great that BDV shows a scale bar, however, it is not captured on screenshots. Given 'best scientific practice' for figures, I guess it wouldn't hurt to just add it by default to all the screenshots?

**Comment by tischi** [comment]
Great idea! 

We cannot copy the scale bar from BDV but I guess we could add code to automatically add an ImageJ scale bar!

**Comment by vzinche** [comment]
That would be amazing, thanks!

**Comment by tischi** [comment]
@vzinche It turns out that it would be quite some work to automatically determine a good looking scale bar. Also, I am afraid that different people will have different taste and requirements. I thus [just changed the screenshot GUI](https://github.com/mobie/mobie-viewer-fiji/commit/4a80a45d97b6506df878d750189c5a84128ec5bc), hinting at the option to add a scale bar:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/2157566/152686013-75d0b047-05c1-43cc-85e0-b0a9388492fe.png">

Do you think that's OK?

**Comment by vzinche** [comment]
I guess you are right with taste and requirements. I like the BDV one, but for the ImageJ one it might really make sense to adjust it manually. But adding this hint is definitely a good idea. 
Btw, is it expected that it only works in mobie-beta for me? In the main mobie it somehow gets the screenshot size in pixels.

**Comment by tischi** [comment]
> Btw, is it expected that it only works in mobie-beta for me? In the main mobie it somehow gets the screenshot size in pixels.

I am not sure about "expected", but in general MoBIE-beta should be better than MoBIE.
