### ISSUE TITLE
New spec for crop transform

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#619]
```
// Serialisation
protected List< String > sources;
protected List< String > sourceNamesAfterTransform;
protected double[] boxMin;
protected double[] boxMax;
protected double[] boxAffine; // places the box into physical space, if null, it will default to identity transform
protected Boolean centerAtOrigin; // if null, it will default to true
protected Boolean rectify;// if null, it will default to true
```

@constantinpape, @martinschorb  what do you think?

**Comment by tischi** [comment]
I think this is better as it is backwards compatible:

```
// Serialisation
	protected List< String > sources;
	protected List< String > sourceNamesAfterTransform;
	protected double[] min; // box min
	protected double[] max; // box max
	protected double[] affine; // from box to physical, if null, it will default to identity transform
	protected Boolean centerAtOrigin; // if null, it will default to true
	protected Boolean rectify;// if null, it will default to true
```

**Comment by martinschorb** [comment]
don't you want to avoid `affine` to not confuse it with the `affine` source transform?

**Comment by tischi** [comment]
@martinschorb I discussed with Constantin and we think `affine` here is a good option.

Also, I think the "bug" that we saw earlier this week was due to something else.
Could you please change the "TEST_new_grid" accordingly such that we could try?

**Comment by martinschorb** [comment]
I find it confusing to have identically named keys with different schemas. This issue we already have with the sources lists and this inconsistency is quite annoying.

**Comment by constantinpape** [comment]
> I find it confusing to have identically named keys with different schemas.

I would be ok with this here, because these names appear on very different levels. But I am pretty agnostic here since it's a new key being introduced, so go with whatever name you like.

But we need to keep the names for `min`, `max`, `centerAtOrigin` and all the source related things to be backward compatible.

**Comment by martinschorb** [comment]
Agree.
My problem with this is that at the parent level `sourceTransforms` there is already a spec for `affine` that contains transformation information as a nested object.
I also find it extremely confusing that different `sourceTransforms` entries (`affine` or `crop` vs. `grid` or `transformedGrid`)  have different specs for their `sources`. (List vs. List of Lists) 
Using dedicated key names with own specs would make everything more clear.
I think we should try to keep things as consistent as possible in the view spec.

**Comment by constantinpape** [comment]
> I also find it extremely confusing that different `sourceTransforms` entries (`affine` or `crop` vs. `grid` or `transformedGrid`) have different specs for their `sources`. (List vs. List of Lists)

This is due to the nature of the transformations and not something we can fix in the short-term. Note that users should not interact with the spec on this level in any case, but rather generate it with mobie-fiji or with the python library.
And developers will need to study the spec description if they want to understand it.
(Also this is largely due to complications in how to specify the grid; we may eventually be able to just pass with a single grid spec since the merged grid is only necessary due to inefficiencies in bdv).

Regarding the name for `affine` here: I will leave this up to you , just let me know what you decide and I will update the jsonschema.

**Comment by martinschorb** [comment]
I am advocating for a bit more specific keys.
`cropAffine` or `boxAffine` just makes things clearer to distinguish from `affine`. The same would hold for something like `gridSources` vs. `sources` ; but here we obviously would run into a backwards-compatibility issue.

**Comment by constantinpape** [comment]
> `cropAffine` or `boxAffine` just makes things clearer to distinguish from `affine`.

Fine with me, please let me know what you want here, @tischi.

> The same would hold for something like `gridSources` vs. `sources` ; but here we obviously would run into a backwards-compatibility issue.

Yeah, this is too much work to change now and would require a proper version bump of the spec, if you want you can open a separate issue in mobie.github,io about it so that we can keep track of it.

**Comment by tischi** [comment]
I changed it to `boxAffine`.
Could you please update TEST_new_grid

**Comment by martinschorb** [comment]
done

**Comment by constantinpape** [comment]
I have also updated the jsonschema accordingly: https://github.com/mobie/mobie.github.io/commit/fcd9416d04b97e089d3a315274cf73865b3f4d00

**Comment by constantinpape** [comment]
This is done as far as I can see.
