### ISSUE TITLE
adjust contrast for float data

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#640]
Hi,

the contrast adjustment for float data in Beta still seems broken.

`/g/emcf/Hamburg_XRay/MoBIE_new`

**Comment by constantinpape** [comment]
I think that we don't have this in any release of MoBIE / MoBIE-beta yet since we are waiting on issues with opening n5 data from s3 to be resolved, e.g. https://github.com/mobie/mobie-viewer-fiji/issues/638. @KateMoreva is working on this; we will ping you as soon as the new release is there and can be tested.

**Comment by constantinpape** [comment]
@martinschorb we have released the new MoBIE-beta version. Can you please check if the issue is fixed now?

**Comment by martinschorb** [comment]
cool, works now. 🚀  Even inverting the contrast!
