### ISSUE TITLE
Cannot open platy from i2k bucket

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#654]
@constantinpape 

[ Plugins › BigDataViewer › OME ZARR › Open OME ZARR From S3... ]

`https://s3.embl.de/i2k-2020/platy-raw.ome.zarr `

Gives me:

```
Caused by: java.lang.UnsupportedOperationException: Could not find multiscales at service endpoint: https://s3.embl.de; bucket: i2k-2020; container path: platy-raw.ome.zarr ; path: ; attribute: multiscales
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.getMultiscale(N5OMEZarrImageLoader.java:260)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.initSetups(N5OMEZarrImageLoader.java:171)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.fetchSequenceDescriptionAndViewRegistrations(N5OMEZarrImageLoader.java:126)
```

Can you open it?

**Comment by constantinpape** [comment]
Yes, I can open it:  (Somehow the default brightness is weird but otherwise it looks good)
![image](https://user-images.githubusercontent.com/4263537/159667508-015738d2-6bae-4b6a-9f19-a2484f1f6e22.png)
![image](https://user-images.githubusercontent.com/4263537/159667116-c25c9482-ca0b-4581-8835-561980a89b21.png)
This is with the latest MoBIE from the main update site.

**Comment by K-Meech** [comment]
@tischi - I can open it on the current develop branch (with the same weird contrast @constantinpape sees)
Have you tried doing a ```mvn clean install```?

**Comment by tischi** [comment]
Wow! I tried everything, also deleted the local maven cache and then I finally found what the issue was!

Can you see it? 😉 

<img width="509" alt="image" src="https://user-images.githubusercontent.com/2157566/159691097-18e7b533-a02b-4845-b6c9-a449e7c23136.png">

**Comment by tischi** [comment]
I think I found out why we have the weird contrast. I made another issue: https://github.com/mobie/mobie-io/issues/88
The data is loaded two times
<img width="718" alt="image" src="https://user-images.githubusercontent.com/2157566/159692233-d5934940-4d9d-4204-b18e-f6ac6d93b949.png">

**Comment by tischi** [comment]
Hard to see, in fact, I had a white space at the end of the URL.

Google tells me the URL are not allowed to contain spaces, thus what about adding below line of code?

```
public class OpenOMEZARRFromS3Command implements Command {

    @Parameter(label = "S3 URL")
    public String s3URL = "https://s3.embl.de/i2k-2020/em-raw.ome.zarr";

    @Parameter ( label = "Log chunk loading" )
    public boolean logChunkLoading = false;

    protected static void openAndShow(String s3URL) throws IOException {
        s3URL = s3URL.replaceAll( "\\s", "" ); // HERE
        SpimData spimData = OMEZarrS3Opener.readURL(s3URL);
        final OMEZarrViewer viewer = new OMEZarrViewer(spimData);
        viewer.show();
    }
```

Or do we want to have this even deeper in the code, e.g. inside ` OMEZarrS3Opener.readURL` or even deeper? Maybe implementing some general `cleanUpURL()` function that we always call?

**Comment by K-Meech** [comment]
Sounds good! If whitespaces aren't allowed in URL, then it makes sense to put it deeper inside ```OmeZarrS3Opener.readURL```, then we don't have to put it after lots of different dialog boxes. It'd be great if it would get called for opening N5 from the S3 too.

**Comment by constantinpape** [comment]
I have fixed the issue with the multiple datasets and the contrast is correct now. Note that there is another small issue with this data due to missing translation in the transformations: https://github.com/mobie/mobie-utils-python/issues/48.
I will look into fixing this, but probably don't have time for it this week (and it's not such a major issue for now; once I fixed it I will replace the metadata).

> Or do we want to have this even deeper in the code, e.g. inside ` OMEZarrS3Opener.readURL` or even deeper? Maybe implementing some general `cleanUpURL()` function that we always call?

I think adding a general function to do this is a good idea; but I would not integrate it too deep in the code and rather call it in the classes implementing the UI commands directly.
I don't think that changing the strings deep in the code is a good idea since it might obfuscate different errors.
