### ISSUE TITLE
Table Annotation: annotate sources & general improvements

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-viewer-fiji#666]
I tried the table annotation for source tables now. In principle it works, but there are a few things that would be nice to improve and that could also benefit the annotation functionality in general.

## UI

The UI says `segment` everywhere. This is a bit weird when annotating sources / images, see the screenshot below.

![image](https://user-images.githubusercontent.com/4263537/161999006-07991c02-5d06-4e33-9a58-8820884424ee.png)

I think we have two options here:
- use a more generic name like `object`
- make the UI reactive, i.e. use `segment` if it's called from a segmentation table, or `source` when it's called from a source annotation table

I would prefer option 2, if that's feasible.

## Color scheme and image coloring

When changing the color of the classes it is not updated in the table or in the image overlay. (See screenshot above).

## Navigation

Navigation for source annotation does not work properly, since "Select segment with label id" does not work. So to get to some image one needs to click through all previous ones.

In general, I think it would be very helpful if one could also use the table for navigating in the annotation mode, i.e. when selecting a row in the table it should be also the one that's being annotated. (And in general it would be nice to sync the table row selection and annotation). This currently does not work, see this video:

https://user-images.githubusercontent.com/4263537/162001222-c4c67e74-b968-4fd2-8fef-a870696b0ef5.mp4

**Comment by tischi** [comment]
I think this is now very convenient. One can Ctrl+LeftClick multiple entities and the then batch assign all of them by clicking the respective annotation class button.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/2157566/164915603-1b94f764-a464-4b34-9b80-d3b05acf8d20.png">

> make the UI reactive, i.e. use segment if it's called from a segmentation table, or source when it's called from a source annotation table

I did this, but was using `region` in instead of source, because, e.g. a `well` could be multiple sources... OK?

Also the `Select region with annotation ID` works now.
What is weird is that once clicking the class button, the region stays selected and thus the coloring scheme does not change to show the classes. I find this very confusing now, but I do remember that was a feature request @vzinche: the argument was that one maybe wants to quickly change to a different class, e.g. because one clicked wrong, which is much more convenient when the region is still selected (and in fact I agree, when being in the `Select previous/next` mode this is more convenient....) One needs to know this and then `Ctrl Shift N` to deselect everything. Complicated...

Essentially, when using below buttons to select _single_ segments it behaves slightly differently, then when selecting  (_multiple_) objects in BDV
<img width="348" alt="image" src="https://user-images.githubusercontent.com/2157566/164915935-9ac91b83-0b75-4020-b3fc-869df7cf8b48.png">

**Comment by tischi** [comment]
> make the UI reactive, i.e. use segment if it's called from a segmentation table, or source when it's called from a source annotation table

we could also just always call it `entity`...

-----


<img width="248" alt="image" src="https://user-images.githubusercontent.com/2157566/164916076-701c9745-ab9e-4ec5-acf6-3653a28a85d8.png">

This is now a bit confusing (`annotation_id` and `Annotate`), because they have nothing to do with each other, but I think this will be hard to change now...

**Comment by constantinpape** [comment]
This works soooo much better now!



> What is weird is that once clicking the class button, the region stays selected and thus the coloring scheme does not change to ...

Ok, it's too late for me to understand this, I will read carefully tomorrow, think about it and then comment on it.



> we could also just always call it `entity`...

I'll make a new issue about this.

**Comment by tischi** [comment]
There was a misunderstanding: I meant to name everything `entity` in the _annotation UI_ (instead of `segment` or `region`).

**Comment by constantinpape** [comment]
> > make the UI reactive, i.e. use segment if it's called from a segmentation table, or source when it's called from a source annotation table
> 
> I did this, but was using `region` in instead of source, because, e.g. a `well` could be multiple sources... OK?

`region` is good

> Also the `Select region with annotation ID` works now.
> What is weird is that once clicking the class button, the region stays selected and thus the coloring scheme does not change to show the classes. I find this very confusing now, but I do remember that was a feature request @vzinche: the argument was that one maybe wants to quickly change to a different class, e.g. because one clicked wrong, which is much more convenient when the region is still selected (and in fact I agree, when being in the `Select previous/next` mode this is more convenient....) One needs to know this and then `Ctrl Shift N` to deselect everything. Complicated...

Ok, I don't understand this. I think we need to discuss via phone / zoom at some point.

> There was a misunderstanding: I meant to name everything `entity` in the _annotation UI_ (instead of `segment` or `region`).

I see, but I think renaming the column is not a bad idea, since `annotation` is a weird name for the column. But let's continue that discussion in #681.

**Comment by constantinpape** [comment]
Two more improvements that would be nice:
- when selecting a source from the table via `Ctrl + Left`, `Next` will not respect that selection and will just jump back to the one that was next prior to the selection. It would be much better if it would respect the selction
- show the name of the currently selected segment / region in the annotation menu. If multiple are selected show the number of selected ones (that would make it a bit more obvious what's going on)

**Comment by tischi** [comment]
> show the name of the currently selected segment / region in the annotation menu. If multiple are selected show the number of selected ones (that would make it a bit more obvious what's going on)

We discussed that the table does that job.

**Comment by tischi** [comment]
I uploaded a new version to MoBIE-beta.
Could you please test the Annotation?

Please note that the sites overlay is shifted, please ignore this for now, I will fix it and upload a new version later (btw: did you update the grid views (center=true/false)?)

**Comment by tischi** [comment]
see https://github.com/mobie/mobie-viewer-fiji/issues/685

**Comment by constantinpape** [comment]
> I uploaded a new version to MoBIE-beta.
> Could you please test the Annotation?

I tested it and it now works as expected. The centering behaviour is also fixed, which now makes this very nice to use!

**Comment by constantinpape** [comment]
This is all done and working now.
