### ISSUE TITLE
Save current view, annotations

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#706]
Hi,

I just noticed that changed LUTs in annotations are not reflected in an exported view.

**Comment by constantinpape** [comment]
What exactly do you mean by this? Changing the random seed for glasbey?
This is indeed currently not saved in the view (maybe we can add it).

Or do you mean something else? Then please make a video or screenshot to illustrate the problem.

**Comment by martinschorb** [comment]
> Changing the random seed for glasbey?

That's one issue:

- open data: LUT is `glasbey`, colors are shades of green.
- change LUT to something else
- change LUT back to `glasbey`, colors are different from the initial ones.


https://user-images.githubusercontent.com/35071867/167105541-b479744d-7017-4e78-9615-ee5256e937bb.mov



When we define views for figures I expect the colors to stay consistent. In this case it is probably due to the random seed.

**Comment by martinschorb** [comment]
forget about the reported issue concerning the exporter. It seems to work as expected.
But the random seeds with glasbey are tricky. Probably we should use other LUTs when producing "publication views".

**Comment by constantinpape** [comment]
I see. Following points:
- viridis and blueWhiteRed colormaps don't make much sense for the annotationId column, they only make sense for ordinal data, but the annotation ids are categorical (sort of)
- when you switch from glasbey to some other colormap and back the random seed indeed changes, that's why the colormap looks different. 
- Maybe we should store the glasbey random seed for `segmentationDisplay`/ `imageAnnotationDisplay`. I will create a separate issue about this.

In the meantime: I think the easiest solution would be if you create an ARGB column with the desired colorscheme, add it to the corresponding default table and then color by it. Let me know if you need any help with this.

**Comment by martinschorb** [comment]
> In the meantime: I think the easiest solution would be if you create an ARGB column with the desired colorscheme

working on that as we chat...
