### ISSUE TITLE
default location values

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#710]
Hi,

before publishing, we should make sure each project has reasonable default locations set when loading.

**Comment by martinschorb** [comment]
I am referring to the "location" default value that is the same for all projects and nonsense for most of them:
![Screenshot 2022-05-17 at 19 02 48](https://user-images.githubusercontent.com/35071867/168870424-fbf929b0-4ac3-4a71-a268-def57c6e6e85.png)

**Comment by constantinpape** [comment]
The way to change this is via the `defaultLocation` field in the dataset: https://github.com/mobie/platybrowser-project/blob/main/data/1.0.1/dataset.json#L2-L8.
@tischi I think we should also change the default here, so that it's empty instead of showing some arbitrary value.

**Comment by martinschorb** [comment]
And it would be also cool to not have to type the entire JSON string into that input field but rather just the three coordinate values. If while parsing it finds `{` as first non-blank char, it could still interpret the input as JSON string to enable more functionality than just `position`.

**Comment by martinschorb** [comment]
Hmm,  it looks like `defaultLocation` is not applied...

https://github.com/mobie/clem-example-project/blob/00cf17306086bfbb615b860fc49414523afb3b9d/data/hela/dataset.json#L3

vs. 

![](https://user-images.githubusercontent.com/35071867/168870424-fbf929b0-4ac3-4a71-a268-def57c6e6e85.png)

**Comment by constantinpape** [comment]
@tischi so I think there are 3 things to potentially fix:
- make sure that the `defaultLocation` field is actually parsed and used (we currently have it in `clem-example-project` and `platybrowser-project`)
- by default (i.e. if `defaultLocation` is not present) leave the location field black instead of putting in an arbitrary default value
- maybe: allow pasting only the position values (see comment by @martinschorb above). I agree that this would be nice to have, but two caveats:
  - copy pasting json formatted strings must still work, since copy and pasting from logged locations is a very common use case for this field
   - Besides position we also support `affine` and `normalizedAffine` here; which both have 12 values; not quite sure how we would handle this since it seems not possible to tell which of these a user has entered from the values alone

**Comment by tischi** [comment]
> And it would be also cool to not have to type the entire JSON string into that input field but rather just the three coordinate values. If while parsing it finds { as first non-blank char, it could still interpret the input as JSON string to enable more functionality than just position.

@martinschorb could you please open a separate issue for this?

**Comment by tischi** [comment]
https://github.com/mobie/mobie-viewer-fiji/pull/730

**Comment by tischi** [comment]
If it is `null` should we put an empty string or something like `{ position(0,0,0), timepoint=0) }`.
The latter would have the advantage the people see what sort of information they could put there.

**Comment by tischi** [comment]
I gave the `defaultLocation` a default value:

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/2157566/169024741-a48d7780-0a4c-47ef-a77a-5ae8c6cb98ed.png">

- [ ] At some point we could put this in the spec.

**Comment by constantinpape** [comment]
> * At some point we could put this in the spec.

I can add it to the comment, but otherwise the spec, i.e. jsonschema, doesn't really have a notion of default values.

**Comment by constantinpape** [comment]
I will go ahead and close this, the origin is a reasonable default, so we don't have to provide this for all projects now.
