### ISSUE TITLE
Window position table

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#769]
Hi,
the tables are all loaded in the same window position on top of each other. 
When we have an annotation table (worst case, highlighting just one source), it will be drawn last and therefore shown on top of all actually useful tables.

Can you change the position of the table windows such that they are placed next to each other instead of on top?
A dirty hack would be to just shift the next table by 200 pixel (or 10% of the screen width) to the right.

**Comment by tischi** [comment]
It does now displaces the table windows along the x-axis, but for me, on Mac, not along the y-axis (although in the code I offset additional the tables it also along the y-axis).
Maybe because the OS tries to keep the whole table within the Desktop?
This is the only line of code I could find where we specify the table size:
`jTable.setPreferredScrollableViewportSize( new Dimension(500, 200) );`
Not sure yet, what is going on.

**Comment by tischi** [comment]
On linux it looks like this:

![image](https://user-images.githubusercontent.com/2157566/172307596-de844476-7df4-465e-9da2-8c17c24d3006.png)


I am specifying the offset in screen _pixels_...is that the best?

**Comment by constantinpape** [comment]
> I am specifying the offset in screen _pixels_...is that the best?

Maybe you could specify in fraction of screensize instead? Screenpixel will make a big difference depending on 1024x768 vs. 3840 x 2400 etc.
