### ISSUE TITLE
dataset.json timepoints

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#778]
I think we may not need `timepoints` in dataset.json anymore.
See: https://github.com/mobie/mobie-viewer-fiji/issues/777

**Comment by constantinpape** [comment]
Ok, we can eventually get rid of them, but we need to discuss versioning of the spec a bit beforehand, also with #772 and #771 in mind.

**Comment by constantinpape** [comment]
@tischi: should we actually remove the `timepoints` field for the new spec update?
I have created https://github.com/mobie/arabidopsis-root-lm-project/pull/8 so that you can check in mobie3. (I have left the `timepoints` field in for now, but you could check if everything works if you load the data without it.)

**Comment by constantinpape** [comment]
Done.
