### ISSUE TITLE
Contrast adjustment precision

### ISSUE THREAD

**Issue by martinschorb** [mobie/mobie-viewer-fiji#825]
Hi,
data we receive from the synchrotron in HH is 32 bit float. Min/Max values are -0.0025, 0.003.

BDV only allows for 2 digits, so setting the contrast is almost impossible. Can this limit be increased to 4 digits?

**Comment by tischi** [comment]
You mean in BDV UI or in the MoBIE UI?

**Comment by martinschorb** [comment]
I think it is a limitation of BDV. But if you can over-rule this using MoBIE's contrast adjustment, that would be enough.

**Comment by martinschorb** [comment]
Hi,

it's in `emcf/Hamburg_XRay/20220522/mobie_demo`

**Comment by tischi** [comment]
In MoBIE, it sort of works, but you have to roughly adjust and then close the dialog and then open again (you may have to do this several times). 

This is due to: https://github.com/mobie/mobie-viewer-fiji/blob/72e7d6f6cab8aea1c222aff4e115b4b200e515f3/src/main/java/org/embl/mobie/viewer/ui/UserInterfaceHelper.java#L149, which sets the step size based on the current range, when the dialog is opened.

<img width="594" alt="image" src="https://user-images.githubusercontent.com/2157566/190999592-ec1b3de3-b586-414e-85f0-e5937ccd8ab8.png">

**Comment by martinschorb** [comment]
ah, cool. This trick I didn't know.
