### ISSUE TITLE
DatasetsCreatorTest has an error

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#830]
@K-Meech 
The tests for the `DatasetsCreatorTest` do not run in the `mobie3` branch.
Would you have time to have a look?

**Comment by K-Meech** [comment]
@tischi - Sorry I was away travelling this week. I can take a look at this! Probably not until near the end of this week though - would that be too late?

**Comment by tischi** [comment]
Fine! Thanks!

**Comment by K-Meech** [comment]
@tischi The tests are throwing errors because the ```serialize``` part of ```DataSourceMapAdaptor``` isn't implemented yet: https://github.com/mobie/mobie-viewer-fiji/blob/mobie3/src/main/java/org/embl/mobie/viewer/serialize/DataSourceMapAdapter.java#L77

Do you have an example of a project with the latest spec? Then I could go ahead and implement this.

**Comment by tischi** [comment]
Thanks a lot for taking the time.

Here is an issue that discusses the latest spec:
https://github.com/mobie/mobie.github.io/issues/88

I think good examples could be:

1. `https://github.com/mobie/plankton-fibsem-project` branch `mobie3`
2. `https://github.com/mobie/covid-if-project` branch `mobie3`

Let me know if you need other examples!
