### ISSUE TITLE
Blending Mode Spec: Alpha instead of sumOccluding

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#839]
@martinschorb @constantinpape 

I think this would make more sense now, agreed?

```
public enum BlendingMode
{
	@SerializedName("sum")
	Sum,
	@SerializedName("alpha") 
	Alpha,
	@SerializedName("sumOccluding") @Deprecated 
	SumOccluding, // use alpha instead
```

**Comment by constantinpape** [comment]
Just to be clear, you propose to rename `sumOccluding` to `alpha` in `blendingMode`?
I am fine with this change, I just find it a bit confusing that you still have `sumOccluding` as deprecated. I would vote to fully remove it if we make this change, since we don't have a way to mark deprecation on the spec level / it would make things unnecessarily complicated.

**Comment by tischi** [comment]
> I would vote to fully remove it if we make this change, since we don't have a way to mark deprecation on the spec level / it would make things unnecessarily complicated.

Fine with me. I just wanted to avoid that we have to reformat all our projects and I could support both `sumOccluding` and `alpha` for some time in the Java code.

**Comment by constantinpape** [comment]
> > 
> 
> Fine with me. I just wanted to avoid that we have to reformat all our projects and I could

I have to do the reformatting for the change to the v3 spec in any case, and I think of the projects where I ran the reformatting already none uses a blending mode.

**Comment by constantinpape** [comment]
I updated the spec accordingly.

**Comment by tischi** [comment]
yes, default is `sum`

**Comment by tischi** [comment]
For the segmentation displays, did we say that `sumOccluding` (now `alpha`) is the default?!
It would make sense. But I cannot find this in my code right now anymore...
