### ISSUE TITLE
TransformedSource

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#861]
I think for sources to be manually transformed within BDV they need to be a `TransformedSource`.

The issue now may be that, while I think that most of our sources are "somewhere" a `TransformedSource` we may have, e.g., a `BoundarySource` wrapped on top such that BDV probably cannot see the  `TransformedSource` anymore.

- [ ] test whether one can currently manually move annotation sources (i.e. `BoundarySources` around in BDV

Another issue is that during serialization we have to capture all transformations. 
Probably we have to unwrap a source sequentially to find all the `TransformedSources` that is may layer on top of each other.

@NicoKiaru could you comment how you handle this currently in bdv-playground?

**Comment by NicoKiaru** [comment]
> could you comment how you handle this currently in bdv-playground?

I'd like to, but I don't get what the problem is. I don't know what a BoundarySource is...

Just a comment on this point:

> I think for sources to be manually transformed within BDV they need to be a TransformedSource.

You need to have a way to store an affine transform, that's right. You can do that with a TransformedSource, but it's not the only option. Actually a TransformedSource is quite limited because the transformation (applied on top of another 'origin' source) is the same for all timepoints.

The other option to store a transform is on an AbstractSpimSource. Because it's part of a SpimData object, each source has a list of affine transform associated (to concatenate to know the final transform). There's a different list for each source and for each timepoint. It's the data model that is used by BigStitcher for instance.

In bdv playground, there's a whole class dedicated of applying an affine transform to a source. You can choose whether you want to concatenate or mutate a transformation, and it applies it differently depending on the original source class (Transformed Source or SpimSource) :

https://github.com/bigdataviewer/bigdataviewer-playground/blob/master/src/main/java/sc/fiji/bdvpg/sourceandconverter/transform/SourceTransformHelper.java

**Comment by tischi** [comment]
Thanks @NicoKiaru ! The `BoundarySource` is not important, it is just an example for the fact that the `SourceAndConverter` that I am adding to BDV may currently not be a `TransformedSource` and therefore I suspect that the manual transformations implemented in BDV may not work.

**Comment by tischi** [comment]
I implemented now code to traverse through the sources, using `SourceWrapper`, and collect all the corresponding transformations.
