### ISSUE TITLE
Link to multiple files (Z,T) in StorageLocation

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#974]
For us, one `Source` is a XYZT image and the `StorageLocation` contains the information where to load the corresponding XYZT data. We never had the use-case where this XYZT data is distributed across multiple files, thus we cannot represent this in our [current implementation of StorageLocation](https://github.com/mobie/mobie-viewer-fiji/blob/main/src/main/java/org/embl/mobie/lib/io/StorageLocation.java). 

Now, e.g., to load HCS data where multiple time-points are distributed across multiple files we need something in `StorageLocation` that can point to multiple files (and express that those files correspond to time-points (and not z-planes)),

_Originally posted by @tischi in https://github.com/mobie/mobie-viewer-fiji/issues/971#issuecomment-1445191586_

**Comment by tischi** [comment]
Note that the "opposite scenario", where one path contains too much data, i.e. multiple channels, is covered as we have the `channel` field which allows one to subset one of the potentially multiple channels contained in the path.

Now we need to support multiple paths, which together contain all the XYZT data that belongs to the `Source` that is represented by the `StorageLocation`. 

 I don't know how many different scenarios we want to cover here. 

A frequent use-case (in HCS) is that there is one file path for each Z and T, so "one plane per file"/

Personally, I like to store my data such that there is one file path for each T while all Z are contained within one file, so, "one volume per file".

**Comment by constantinpape** [comment]
Ok, I understand. 

- For the `T` case: in principle we would not need to solve this via the `storageLocation` at all: we have `timepoint` in the `mergedGrid`, so you could just add the files for the timepoints as individual sources, and then "stitch" across time by having a `mergedGrid` per timepoint. (I am not sure if this is actually a good solution in terms of performance, but for completeness we should at least consider this).
- For the storage location: I think having a map/dictionary with timepoints as keys and filepaths as value is probably the best solution if we want to support this. 
- Regarding the spec: in general we can't map any of this to the spec yet, since we don't even have tifs listed in there -- and I think that's fine for now, it just means that you can't serialize something opened via the HCS opener as a MoBIE project. (Maybe we want to support this eventually to support reproducible views etc., but for now I would say go ahead with what works for you, and we can worry about mapping this to the spec later -- just one point; if we have major changes to existing concepts, e.g. having a map of timepoints to filepaths, I think it's best if that's done by a new class that would then also correspond to a new concept in the spec, e.g. `HCSSource`).

**Comment by tischi** [comment]
Thanks!

- `mergedGrid.timepoint`: Interesting :-) I cannot find this in the Java code, do you know whether (and how) we use this somewhere? Instead, in the Java code I found a `TimepointsTransformation`, which could be used to move sources along the time axis; do you have this in the spec?
- `storageLocation`: I will then add some kind of map for T and Z, not sure exactly how yet to have it cover most cases...
- `spec`: I did not think we should add this to the spec, I thought of adding this to the Java code just for opening data that are _not_ a MoBIE project.

**Comment by constantinpape** [comment]
> * `mergedGrid.timepoint`: Interesting :-) I cannot find this in the Java code, do you know whether (and how) we use this somewhere? Instead, in the Java code I found a `TimepointsTransformation`, which could be used to move sources along the time axis; do you have this in the spec?

I double checked, and we actually don't have this for the `mergedGrid` in the spec right now, only for the `transformedGrid`, see https://github.com/mobie/mobie.github.io/blob/master/schema/view.schema.json#L718.
I don't think we use it for the `transformedGrid` in any of the current projects yet. If it helps we could easily add it for the `mergedGrid`.

> * `storageLocation`: I will then add some kind of map for T and Z, not sure exactly how yet to have it cover most cases...

Makes sense. (And I think this is probably a better solution than via `timepoints` in the `mergedGrid`, but I just wanted to mention it earlier for completeness).

> * `spec`: I did not think we should add this to the spec, I thought of adding this to the Java code just for opening data that are _not_ a MoBIE project.

Sounds good. (I think it may make sense to update this at some point to make the CLI more reproducible, but we don't need to worry about this now.)

**Comment by tischi** [comment]
It is a bit of a hack but I could fix this by introducing a new class:

```
public class Site extends StorageLocation
{
	private final String name;
	private int[] dimensions;
	private Map< TPosition, Map< ZPosition, String > > paths = new LinkedHashMap();
	private VoxelDimensions voxelDimensions;
	private ImageDataFormat imageDataFormat;
       ...
}
```
