### ISSUE TITLE
HCS Opener: Bio-Formats window popping up during loading

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#982]
@ThomasMicroscopy reported:

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/2157566/222063287-adc2e8e9-6750-4d09-9aa8-833ea4f4a223.png">

I cannot reproduce this.

@ThomasMicroscopy there is a file in the folder of your images ending on `.xml`, could you please temporarily rename this to ending on `.xml-not` and let me know if the Bio-Formats window still pops up?

**Comment by tischi** [comment]
Possibly related: https://imagesc.zulipchat.com/#narrow/stream/327238-Fiji/topic/Do.20not.20use.20Bio-Formats

**Comment by ThomasMicroscopy** [comment]
Indeed, this Window pops up when I want to import Operetta/Harmony images into Fiji using Bioformats. This is how PE advices to open their files in Fiji:  "Drag the xxx.xml" index file onto Fiji, then I can enter the number of tiff files in the folder that I want to open.  I had indeed wondering if the xml was the cause.  Today, I don't observe the issue anymore, but there was an update of MoBIE that I did first.

**Comment by ThomasMicroscopy** [comment]
Hmm, now I observed it again.  Not sure what is going on. It seems the the main plate image overview window is freezing at some point. Maybe if it freezes, the extra pop-up doesn't happen anymore.

**Comment by ThomasMicroscopy** [comment]
ok, 100% sure, but I didn't have a pop-up now with the xml renamed, but after renaming it back to xml, I had the Bioformats Import options pop up again, under the following conditions: I opened the folder with the HCS Dataset import, and didn't touch the well preview window - it shows about 10 wells in the top right area (> 20 seconds or so). After a while, I started to zoom out, until I saw the whole plate, then the "Bioformats import" dialog popped-up.  More or less, then also the error log in the console showed up, and the well preview window froze up - that is while the little overview on the left shows the zooming - in and out, the wells themselves are frozen, and don't update anymore.

So, to summarise, quite likely, this pop-up happens, when the xml is there.
<img width="1214" alt="Screenshot 2023-03-02 at 14 33 28" src="https://user-images.githubusercontent.com/126269188/222453771-b83c6dab-caa1-4e8e-86bc-a978cd121c0a.png">

Here is then the situation with the frozen window.  while only the green frame in the left top zooms, the images don't zoom, or cannot even be paned. 


<img width="1106" alt="Screenshot 2023-03-02 at 14 33 53" src="https://user-images.githubusercontent.com/126269188/222454937-4371c58f-03da-46dc-b017-17fd0fa95fec.png">

Here is a demonstration where the freezing happened already without doing initially anything in the well window (went away from the desk for a while). After I came back, I dragged the window larger, but as one can see, the wells didn't update.  This was after a complete new start of Fiji, and by adding the two missing files back. So that didn't seem to make a difference.


<img width="1714" alt="Screenshot 2023-03-02 at 15 16 50" src="https://user-images.githubusercontent.com/126269188/222455362-bb66f69d-53c5-41eb-9809-1ef8fd43f85a.png">

These are the two empty files which I added back into the folder with the 2110 tiff images. As one can see, they are only a few kb, no image data. But right now, it doesn't seem to make a difference if they are in the image folder or not, still getting error messages in the console.

<img width="519" alt="Screenshot 2023-03-02 at 13 50 43" src="https://user-images.githubusercontent.com/126269188/222456026-c2a3da62-694e-468b-a3b2-b22e9de150a8.png">

**Comment by tischi** [comment]
Thank you @ThomasMicroscopy for the report.

It is a bit mysterious as I cannot reproduce the **Bio-Formats issue** on my computer even with the xml present. 
I will anyway try to improve this.

Regarding the **freezing issue**: this is probably something else that we should discuss separately here:
https://github.com/mobie/mobie-viewer-fiji/issues/985

**Comment by tischi** [comment]
I think this was due to the `.*` files.
