### ISSUE TITLE
HCS Opener: best viewing practice

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-viewer-fiji#986]
@ThomasMicroscopy
@tibuch 
@constantinpape 

Would you think it makes sense to advice as best practice **not to zoom out** to the full plate, but rather stay zoomed in on a couple of wells and then use the table to navigate to different parts of the plate?

Would that work for your use-cases?

**Comment by ThomasMicroscopy** [comment]
I think usage can vary.  I would think it would be very useful (and that's what I am looking for) to have an overview of all wells, to see how the experiment went, and then zoom in on some wells. I know that with high magnification one needs many fields to get a good coverage of a well, and then one ends up with a lot of data, which makes it slow. I guess that's why people use pyramidal data, i.e. several resolutions. How to best approach this is not clear to me. Your lazy approach is perhaps not bad, where it sort of builds up, you could zoom in on a particular area which would then build up faster.

With regard to the Operetta/Harmony, I don't think they generate any thumbnails beforehand. You click on individual wells on the layout to look at image data, but if you want to have an overview of all, you have to select all wells/fields and it slowly generates a low res overview of the wells (that can be saved as image), which doesn't allow zoom in.  
On the other hand, it seems that Mol Devices with MetaXpress generates thumbnails during recording, so that a plate overview can displayed fast, and individual wells can then still be viewed at high-res. 
The BioP Operetta Importer (in Fiji) can convert a folder of high-res images into downsamples images. Those would load faster. So a preprocessing round with that could help - however maintaining then the ability to zoom in to high res would be tedious, if no precise folder structure is imposed.

**Comment by tischi** [comment]
Thanks @ThomasMicroscopy, in fact I wondered already whether I could create low-res versions on-the-fly.
https://imagesc.zulipchat.com/#narrow/stream/327326-BigDataViewer/topic/Vieweing.20big.20chunked.20non-pyramidal.20data

This is quite some engineering though; but maybe cool, I don't know...

**Comment by tischi** [comment]
Closing in favour of #991
